In [1]:
#Import library
import requests
import pandas as pd
import sqlite3

In [ ]:
# =====================
# CONFIG
# =====================

API_KEY = "Your API Key here"
BASE_URL = "https://financialmodelingprep.com/stable"

SYMBOLS = ["AMZN", "GOOGL"]
MARKET_INDEX = "^IXIC"

START_DATE = "2024-09-24"
END_DATE = "2025-10-06"

In [ ]:
#Get income statement
def get_quarterly_income(symbol):
    url = (
        f"{BASE_URL}/income-statement"
        f"?symbol={symbol}"
        f"&period=quarter"
        f"&limit=5"
        f"&apikey={API_KEY}"
    )

    response = requests.get(url)
    response.raise_for_status()

    data = response.json()
    df = pd.DataFrame(data)
    df["symbol"] = symbol

    return df

In [ ]:
#Get stock price
def get_eod_full_prices(symbol):
    url = (
        f"{BASE_URL}/historical-price-eod/full"
        f"?symbol={symbol}"
        f"&from={START_DATE}"
        f"&to={END_DATE}"
        f"&apikey={API_KEY}"
    )

    response = requests.get(url)
    response.raise_for_status()

    data = response.json()
    df = pd.DataFrame(data)
    df["symbol"] = symbol

    return df

In [ ]:
#Income statement to dataframe
earnings_df = pd.concat(
    [get_quarterly_income(symbol) for symbol in SYMBOLS],
    ignore_index=True
)

earnings_df

,date,symbol,reportedCurrency,cik,filingDate,acceptedDate,fiscalYear,period,revenue,costOfRevenue,...,netIncomeFromContinuingOperations,netIncomeFromDiscontinuedOperations,otherAdjustmentsToNetIncome,netIncome,netIncomeDeductions,bottomLineNetIncome,eps,epsDiluted,weightedAverageShsOut,weightedAverageShsOutDil
0,2025-09-30,AMZN,USD,0001018724,2025-10-31,2025-10-30 18:18:21,2025,Q3,180169000000,88670000000,...,21260000000,0,-73000000,21187000000,0,21187000000,1.98,1.95,10674000000,10845000000
1,2025-06-30,AMZN,USD,0001018724,2025-08-01,2025-07-31 18:13:08,2025,Q2,167702000000,80809000000,...,18179000000,0,0,18164000000,0,18164000000,1.71,1.68,10637000000,10806000000
2,2025-03-31,AMZN,USD,0001018724,2025-05-02,2025-05-01 18:14:53,2025,Q1,155667000000,76976000000,...,17127000000,0,0,17127000000,0,17127000000,1.62,1.59,10603000000,10793000000
3,2024-12-31,AMZN,USD,0001018724,2025-02-07,2025-02-06 18:40:29,2024,Q4,187792000000,98893000000,...,20004000000,0,0,20004000000,0,20004000000,1.90,1.86,10473000000,10721000000
4,2024-09-30,AMZN,USD,0001018724,2024-11-01,2024-10-31 18:44:54,2024,Q3,158877000000,80977000000,...,15331000000,0,-3000000,15328000000,0,15328000000,1.46,1.43,10501000000,10735000000
5,2025-09-30,GOOGL,USD,0001652044,2025-10-30,2025-10-29 21:55:01,2025,Q3,102346000000,41369000000,...,34979000000,0,0,34979000000,0,34979000000,2.89,2.87,12086000000,12203000000
6,2025-06-30,GOOGL,USD,0001652044,2025-07-24,2025-07-23 19:44:01,2025,Q2,96428000000,39039000000,...,28196000000,0,0,28196000000,0,28196000000,2.33,2.31,12122000000,12198000000
7,2025-03-31,GOOGL,USD,0001652044,2025-04-25,2025-04-24 21:05:29,2025,Q1,90234000000,36361000000,...,34540000000,0,0,34540000000,0,34540000000,2.84,2.81,12183000000,12291000000
8,2024-12-31,GOOGL,USD,0001652044,2025-02-05,2025-02-04 20:41:40,2024,Q4,96469000000,40613000000,...,26536000000,0,0,26536000000,0,26536000000,2.17,2.15,12228000000,12348000000
9,2024-09-30,GOOGL,USD,0001652044,2024-10-30,2024-10-29 19:33:10,2024,Q3,88268000000,36474000000,...,26301000000,0,0,26301000000,0,26301000000,2.14,2.12,12290000000,12419000000

In [ ]:
#Stock price to dataframe
prices_df = pd.concat(
    [get_eod_full_prices(symbol) for symbol in SYMBOLS],
    ignore_index=True
)

prices_df.head()

,symbol,date,open,high,low,close,volume,change,changePercent,vwap
0,AMZN,2025-10-06,221.00,221.73,216.03,220.90,43690900,-0.10,-0.045249,219.9150
1,AMZN,2025-10-03,223.44,224.20,219.34,219.51,43639033,-3.93,-1.760000,221.6225
2,AMZN,2025-10-02,221.01,222.81,218.95,222.41,41258600,1.40,0.633460,221.2950
3,AMZN,2025-10-01,217.36,222.15,216.61,220.63,43933834,3.27,1.500000,219.1875
4,AMZN,2025-09-30,222.03,222.24,217.89,219.57,48396400,-2.46,-1.110000,220.4325

In [ ]:
#Market price to dataframe
market_df = get_eod_full_prices(MARKET_INDEX)
market_df.rename(columns={"symbol": "index_symbol"}, inplace=True)

market_df.head()

,index_symbol,date,open,high,low,close,volume,change,changePercent,vwap
0,^IXIC,2025-10-06,22894.35,22991.72,22827.56,22941.67,10468830000,47.32,0.20669,22913.8250
1,^IXIC,2025-10-03,22886.16,22925.43,22695.82,22780.51,10515730000,-105.65,-0.46163,22821.9800
2,^IXIC,2025-10-02,22885.91,22900.60,22729.75,22844.05,9633200000,-41.85,-0.18291,22840.0775
3,^IXIC,2025-10-01,22530.95,22782.58,22516.74,22755.16,10043980000,224.21,0.99512,22646.3575
4,^IXIC,2025-09-30,22580.36,22671.39,22493.96,22660.01,8928070000,79.65,0.35274,22601.4300

In [ ]:
#Export to csv
earnings_df.to_csv("raw_quarterly_earnings.csv", index=False)
prices_df.to_csv("raw_daily_stock_prices.csv", index=False)
market_df.to_csv("raw_market_index_prices.csv", index=False)